// Generated by CoffeeScript 1.6.3
(function() {
  var D3Model, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  D3Model = (function(_super) {
    __extends(D3Model, _super);

    function D3Model() {
      _ref = D3Model.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return D3Model;

  })(Backbone.Model);

}).call(this);
