// Generated by CoffeeScript 1.6.3
(function() {
  var D3View, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  D3View = (function(_super) {
    __extends(D3View, _super);

    function D3View() {
      _ref = D3View.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return D3View;

  })(Backbone.View);

}).call(this);
